### ISSUE TITLE
0.1.2 roadmap

### ISSUE THREAD

**Issue by gfudenberg** [open2c/polychrom#39]
- [ ] rename branch `master` → `main`
- [ ] add get_requirements to setup.py, move install instructions to readme
- [ ] change functions with camelCase → snake_case
- [ ] remove random things (e.g. Untitled.ipynb)
- [ ] finalize decision on ./cli/ (delete?)

- [ ] create ./polychrom/visualization/ 
  - [ ] migrate ./polychrom/pymol_show.py into this
  - [ ] move ./utilities/ into this and installpymol.sh
  - [ ] longer term see below
  
- [ ] legacy: clean up and rename into `./experimental/` namespace

- [ ] migrate 1D extrusion code out of library
  - [ ]  keep the milker, in new ./polychrom/scheduler.py that can update bonds. Try to remain agnostic to how bond is generated & generalize the function.
  - [ ] Clarify that the scope of polychrom is doing polymer simulations, including those that can have non-equilibrium update rules (in readme/docs). 

- [ ] extend examples
  - [ ] fix example.ipynb, currently breaks due to chain format (maybe default to CPU as well)
  - [ ] new notebooks using the polymer_analyses functions
  - [ ] extrusion 1D+3D example that relies on migrated extrusion scripts
  - [ ] add yeast interphase model to examples
  - [ ] replace storage_formats example with an ipynb that explains how to access & process saved data 
  
- [ ] rename hdf5_format.py module to `storage.py`
- [ ] refactor polymerutils: rotation matrix joins polymer_analyses, everything else to storage.py

further future:
- [ ] discuss where to put ndarray_groupby_aggregate/streaming_ndarray_agg
- [ ] develop visualization for polychrom, potentially based off of nglutils
- [ ] extend scheduler to manage non-bonded forces

**Comment by gfudenberg** [comment]
Qs:
- should we remove simulation.show?
- should we consider deprecating rasmol generally?
- should the try statement be removed & _polymer_math be assumed to work in polymer_analyses? https://github.com/gfudenberg/polychrom/blob/bdbd0687227ed7cbbf2fa2c088a5aeb0289da194/polychrom/polymer_analyses.py#L46

**Comment by mimakaev** [comment]
Yes on removing simulation.show and deprecating rasmol. 

No about the try statement so far: it is for sphynx & readthedocs. Sphynx doesn't compile the module and imports it "as is" - which is why polymer math isn't there. There probably is a more graceful solution for this... but dealing with Sphynx always feels like some hardcore archeology... and I'm not ready.
